
# This file was *autogenerated* from the file run_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_10 = Integer(10)
load("LLL_algorithm.sage")
runtimes = []
for i in range(_sage_const_0 ,_sage_const_10 ):
	runtimes.append(_sage_const_0p0 )
	for k in range(_sage_const_0 ,_sage_const_1 ):
		r = _sage_const_0 
		while(r!=i+_sage_const_2 ):
			A = random_matrix(ZZ, i+_sage_const_2 )
			r = A.rank()
		t = cputime()
		res = LLL(A)
		print A
		print "Hello World"
		print res
		runtimes[i] = runtimes[i] + cputime(t)*_sage_const_0p1 
print(runtimes)

