
# This file was *autogenerated* from the file short_pad.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_60 = Integer(60); _sage_const_256 = Integer(256)
length_N = _sage_const_256 
p = next_prime(_sage_const_2 **int(round(length_N/_sage_const_2 )))
q = next_prime(round(pi.n()*p))
N = p*q
e = _sage_const_3 
print "N"
print N
ZmodN = Zmod(N)

M1 = ZZ.random_element(_sage_const_0 ,_sage_const_2 **_sage_const_60 )
diff = ZZ.random_element(_sage_const_0 ,_sage_const_2 **_sage_const_6 )
M2   =  M1 + diff 
C1   =  ZmodN(M1)**e
C2   =  ZmodN(M2)**e
a = _sage_const_1  
b = diff 

R = PolynomialRing(ZmodN, names=('x',)); (x,) = R._first_ngens(1)
g1 = x**e - C1
g2 = (x+diff)**e - C2

print g2.gcd(g1)

