
# This file was *autogenerated* from the file 2test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_384635054622 = Integer(384635054622); _sage_const_0p01 = RealNumber('0.01'); _sage_const_5 = Integer(5); _sage_const_1571023 = Integer(1571023); _sage_const_197314381133 = Integer(197314381133); _sage_const_10 = Integer(10); _sage_const_1379321 = Integer(1379321); _sage_const_612301 = Integer(612301)
load("coppersmith_method.sage")
p  = _sage_const_1379321 
q  = _sage_const_1571023 
n  = p*q
e  = _sage_const_5 
d  = _sage_const_197314381133 
M  = _sage_const_612301 
for i in range(-_sage_const_10 ,_sage_const_10 ):
	MA = M + i
	C  =  _sage_const_384635054622 
	R = ZZ ['x']; (x,) = R._first_ngens(1)
	f = ( MA + x ) ** e - C
	print i
	print coppersmith(f , p *q , _sage_const_0p01  , True)


