
# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_955769 = Integer(955769); _sage_const_17851762484 = Integer(17851762484); _sage_const_497314381133 = Integer(497314381133); _sage_const_423918 = Integer(423918); _sage_const_5 = Integer(5); _sage_const_423909 = Integer(423909); _sage_const_650413 = Integer(650413); _sage_const_0p1 = RealNumber('0.1')
load("coppersmith_method.sage")
p  = _sage_const_955769 
q  = _sage_const_650413 
n  = p*q
e  = _sage_const_5 
d  = _sage_const_497314381133 
M  = _sage_const_423909 
MA = _sage_const_423918 
C  = _sage_const_17851762484  
R = ZZ ['x']; (x,) = R._first_ngens(1)
f = ( MA + x ) ** e - C
print coppersmith(f , p *q , _sage_const_0p1  , True)

